project_name: loggo
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Aurelio Calegari (aurcbot@gmail.com)
    description: Rich Terminal User Interface for JSON logs
    homepage: https://github.com/aurc/loggo
    license: MIT
    formats:
      - deb
      - rpm
      - apk
brews:
  -
    name: loggo
    # GOARM to specify which 32-bit arm version to use if there are multiple versions
    # from the build section. Brew formulas support atm only one 32-bit version.
    # Default is 6 for all artifacts or each id if there a multiple versions.
    goarm: 6

    tap:
      owner: aurc
      name: homebrew-loggo
      branch: main
    #      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
    #      token: "{{ .Env.HOMEBREW_LOGGO_GITHUB_TOKEN }}"

    url_template: "https://github.com/aurc/loggo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: aurc_bot
      email: aurcbot@gmail.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: "How to use this binary"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/aurc/homebrew-loggo"

    # Template of your app's description.
    # Default is empty.
    description: "Rich Terminal User Interface for JSON logs"

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

