// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: loggo/service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoggoClient is the client API for Loggo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggoClient interface {
	LogStream(ctx context.Context, in *LogEntryRequest, opts ...grpc.CallOption) (Loggo_LogStreamClient, error)
}

type loggoClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggoClient(cc grpc.ClientConnInterface) LoggoClient {
	return &loggoClient{cc}
}

func (c *loggoClient) LogStream(ctx context.Context, in *LogEntryRequest, opts ...grpc.CallOption) (Loggo_LogStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Loggo_ServiceDesc.Streams[0], "/loggo.Loggo/LogStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &loggoLogStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Loggo_LogStreamClient interface {
	Recv() (*LogEntryResponse, error)
	grpc.ClientStream
}

type loggoLogStreamClient struct {
	grpc.ClientStream
}

func (x *loggoLogStreamClient) Recv() (*LogEntryResponse, error) {
	m := new(LogEntryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LoggoServer is the server API for Loggo service.
// All implementations must embed UnimplementedLoggoServer
// for forward compatibility
type LoggoServer interface {
	LogStream(*LogEntryRequest, Loggo_LogStreamServer) error
	mustEmbedUnimplementedLoggoServer()
}

// UnimplementedLoggoServer must be embedded to have forward compatible implementations.
type UnimplementedLoggoServer struct {
}

func (UnimplementedLoggoServer) LogStream(*LogEntryRequest, Loggo_LogStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LogStream not implemented")
}
func (UnimplementedLoggoServer) mustEmbedUnimplementedLoggoServer() {}

// UnsafeLoggoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggoServer will
// result in compilation errors.
type UnsafeLoggoServer interface {
	mustEmbedUnimplementedLoggoServer()
}

func RegisterLoggoServer(s grpc.ServiceRegistrar, srv LoggoServer) {
	s.RegisterService(&Loggo_ServiceDesc, srv)
}

func _Loggo_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogEntryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggoServer).LogStream(m, &loggoLogStreamServer{stream})
}

type Loggo_LogStreamServer interface {
	Send(*LogEntryResponse) error
	grpc.ServerStream
}

type loggoLogStreamServer struct {
	grpc.ServerStream
}

func (x *loggoLogStreamServer) Send(m *LogEntryResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Loggo_ServiceDesc is the grpc.ServiceDesc for Loggo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Loggo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loggo.Loggo",
	HandlerType: (*LoggoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LogStream",
			Handler:       _Loggo_LogStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loggo/service.proto",
}
